// Code generated by tools/c8ygen; DO NOT EDIT.
//
// Source: docs/c8y-oas.yml
// Regenerate with: task generate  (or: go generate ./...)
//
// This file is the mechanical, 1:1-with-OAS substrate (Layer 0). The ergonomic
// public API (resolvers, option structs, upsert, iterators) is hand-written and
// lives outside this package. See docs/API_GEN.md.

package notification2

import (
	"github.com/reubenmiller/go-c8y/v2/pkg/c8y/api/pagination"
)

// ListOptions to use when searching for notification subscriptions.
type ListOptions struct {
	// The context to which the subscription is associated.
	Context string `url:"context,omitempty"`

	// The managed object ID to which the subscription is associated.
	Source string `url:"source,omitempty"`

	// The subscription name by which filtering will be done.
	Subscription string `url:"subscription,omitempty"`

	// The type used to filter subscriptions. This will check the subscription's `subscriptionFilter.typeFilter` field.
	TypeFilter string `url:"typeFilter,omitempty"`

	pagination.PaginationOptions
}
