package api_test

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/reubenmiller/go-c8y/internal/pkg/fakeserver"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestFakeServer_MatchesGolden loads golden files recorded from a live server
// (TEST_MODE=record) and replays the same requests against the fake server,
// then compares status codes and response JSON structure.
//
// This test is a validation tool, not a hard gate — run it periodically to
// catch drift between the fake and real server.
//
// To generate golden files:
//
//	TEST_MODE=record go test -count=1 -v ./test/c8y_api_test/...
//
// To validate:
//
//	TEST_MODE=offline go test -count=1 -v -run TestFakeServer_MatchesGolden ./test/c8y_api_test/...
func TestFakeServer_MatchesGolden(t *testing.T) {
	goldenDir := filepath.Join("testdata", "golden")
	entries, err := os.ReadDir(goldenDir)
	if os.IsNotExist(err) {
		t.Skip("no golden files found — run tests with TEST_MODE=record first")
	}
	require.NoError(t, err)

	if len(entries) == 0 {
		t.Skip("golden directory is empty — run tests with TEST_MODE=record first")
	}

	srv := fakeserver.New(t)

	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".json" {
			continue
		}
		// Skip comparison report files generated by previous runs
		if strings.Contains(entry.Name(), ".comparison.") || strings.HasSuffix(entry.Name(), ".comparison.json") {
			continue
		}

		testName := entry.Name()[:len(entry.Name())-len(".json")]

		t.Run(testName, func(t *testing.T) {
			goldenPath := filepath.Join(goldenDir, entry.Name())
			golden, err := fakeserver.LoadGoldenFile(goldenPath)
			require.NoError(t, err, "failed to load golden file: %s", goldenPath)

			if len(golden) == 0 {
				t.Skip("golden file is empty")
			}

			// Replay each recorded request against the fake server
			var fakeRecords []fakeserver.RequestResponsePair
			for _, g := range golden {
				resp := srv.Replay(g.Request)
				fakeRecords = append(fakeRecords, fakeserver.RequestResponsePair{
					Request:  g.Request,
					Response: resp,
				})
			}

			results, allPass := fakeserver.CompareRecords(golden, fakeRecords)
			if !allPass {
				for _, r := range results {
					if !r.StatusMatch {
						t.Errorf("%s %s: status mismatch: live=%d fake=%d",
							r.Request.Method, r.Request.Path,
							r.LiveStatus, r.FakeStatus)
					}
					if !r.KeysMatch && len(r.MissingKeys) > 0 {
						t.Errorf("%s %s: missing keys in fake response: %v",
							r.Request.Method, r.Request.Path,
							r.MissingKeys)
					}
				}
			}

			// Log extra keys as informational (not failures)
			for _, r := range results {
				if len(r.ExtraKeys) > 0 {
					t.Logf("%s %s: extra keys in fake response (OK): %v",
						r.Request.Method, r.Request.Path,
						r.ExtraKeys)
				}
			}

			// Write a comparison report alongside the golden file
			reportPath := filepath.Join(goldenDir, testName+".comparison.json")
			reportData, _ := json.MarshalIndent(results, "", "  ")
			if writeErr := os.WriteFile(reportPath, reportData, 0o644); writeErr != nil {
				t.Logf("WARNING: failed to write comparison report: %v", writeErr)
			}

			assert.True(t, allPass, "golden file comparison failed for %s", testName)
		})
	}
}
