version: "2"

run:
  timeout: 30m

linters:
  enable:
    - misspell
  disable:
    - errcheck
  settings:
    govet:
      disable:
        - fieldalignment
    misspell:
      # Correct spellings using locale preferences for US or UK.
      # Setting locale to US will correct the British spelling of 'colour' to 'color'.
      # Default is to use a neutral variety of English.
      locale: US
      # Treat 'mosquitto' as a correctly spelled word.
      extra-words:
        - typo: mosquitto
          correction: mosquitto

formatters:
  enable:
    - goimports
    - gofmt
