language: go

addons:
  sonarcloud:
    organization: "sonarcloud_organization_key" # the key of the org you chose at step #3
    token:
      secure: ********* # encrypted value of your token

go:
  - 1.11.x
  - master

script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner