environment:
  nuget_apikey:
    secure: asdfasdf/asdfasdfasdf
  C8Y_HOST:
    secure: 1mpbPj8TYp5TrBamoABxWATQWb1t1BIsdyos8N8R60QOVB1puaWvH/yuw+0ClWjk
  C8Y_TENANT:
    secure: dldySxQAn1jXmUCoZFkKRw==
  C8Y_USER:
    secure: 7nnf6/dt+mNSq5pVZrdXBw==
  C8Y_PASSWORD:
    secure: olAYnZxd7FOGGVMy0pgrTcl+LcNGEtraxIkPJftUndk=
image: 
  - Visual Studio 2019
  - Ubuntu
  - macos

install:
- ps: ./scripts/build-powershell/install.ps1

build_script:
- ps: ./scripts/build-powershell/build.ps1

test_script:
- ps: ./scripts/build-powershell/test.ci.ps1

#after_test:
#- ps: ./scripts/build-powershell/publish.ps1

for:
-
  matrix:
    only:
      - image: Ubuntu

  build_script:
  - echo Ubuntu build script