version: '3'

env:
  ENV: testing

dotenv: ['.env', 'c8y.env', '{{.ENV}}/c8y.env', '{{.HOME}}/c8y.env']

tasks:
  test:
    desc: Test all packages
    cmds:
      - task: test-c8y
      - task: test-microservice
      - task: test-race

  test-c8y:
    desc: Test c8y package
    cmds:
      - go test -v -timeout 30m github.com/reubenmiller/go-c8y/test/c8y_test

  test-microservice:
    desc: Test microservice package
    cmds:
      - go test -v -timeout 30m github.com/reubenmiller/go-c8y/test/microservice_test

  test-race:
    desc: Test for race conditions
    cmds:
      - go test -race -timeout 30s github.com/reubenmiller/go-c8y/test/c8y_test -run "^(TestRealtimeSubscriptions_Unsubscribe)$"

  lint:
    desc: Linting
    cmds:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
      - golangci-lint run -c .golangci.yml

  docs:
    desc: Launch go doc webserver
    cmds:
      - go install golang.org/x/tools/cmd/godoc@latest
      - godoc -http=":6060"
