// Code generated by tools/c8ygen; DO NOT EDIT.
//
// Source: docs/c8y-oas.yml
// Regenerate with: task generate  (or: go generate ./...)
//
// This file is the mechanical, 1:1-with-OAS substrate (Layer 0). The ergonomic
// public API (resolvers, option structs, upsert, iterators) is hand-written and
// lives outside this package. See docs/API_GEN.md.

package model

// Typed well-known custom fragments. Each implements model.Fragment
// (FragmentKey), so it can be used on the write side (CreateOptions.Fragments)
// and decoded on the read side (jsonmodels.GetFragment).

// Position Reports the geographical location of an asset in terms of latitude, longitude and altitude.
type Position struct {
	Alt              float64 `json:"alt,omitempty"`
	Lat              float64 `json:"lat,omitempty"`
	Lng              float64 `json:"lng,omitempty"`
	ReportReason     string  `json:"reportReason,omitempty"`
	TrackingProtocol string  `json:"trackingProtocol,omitempty"`
}

// FragmentKey implements model.Fragment.
func (Position) FragmentKey() string { return "c8y_Position" }

// Hardware Contains basic hardware information for a device, such as make and serial number. Often, the hardware serial number is printed on the board of the device or on an asset tag on the device to uniquely identify the device within all devices of the same make.
type Hardware struct {
	Model        string `json:"model,omitempty"`
	Revision     string `json:"revision,omitempty"`
	SerialNumber string `json:"serialNumber,omitempty"`
}

// FragmentKey implements model.Fragment.
func (Hardware) FragmentKey() string { return "c8y_Hardware" }

// Firmware Contains information on a device's firmware. In the inventory, `c8y_Firmware` represents the currently installed firmware on the device. As part of an operation, `c8y_Firmware` requests the device to install the indicated firmware. To enable firmware installation through the user interface, add `c8y_Firmware` to the list of supported operations.
type Firmware struct {
	Name    string `json:"name,omitempty"`
	URL     string `json:"url,omitempty"`
	Version string `json:"version,omitempty"`
}

// FragmentKey implements model.Fragment.
func (Firmware) FragmentKey() string { return "c8y_Firmware" }

// Mobile Holds basic connectivity-related information, such as the equipment identifier of the modem (IMEI) in the device. This identifier is globally unique and often used to identify a mobile device.
type Mobile struct {
	CellID string `json:"cellId,omitempty"`
	Iccid  string `json:"iccid,omitempty"`
	Imei   string `json:"imei,omitempty"`
}

// FragmentKey implements model.Fragment.
func (Mobile) FragmentKey() string { return "c8y_Mobile" }
