#
# Module manifest for module 'PSc8y'
#
# Generated by: Reuben Miller
#
# Generated on: 2019.10.16
#

@{

# Script module or binary module file associated with this manifest.
RootModule = './PSc8y.psm1'

# Version number of this module.
ModuleVersion = '1.0.1'

# Supported PSEditions
CompatiblePSEditions = @(
    "Desktop",
    "Core"
)

# ID used to uniquely identify this module
GUID = '9b4ebc35-bd61-4d07-a528-81c5733d0732'

# Author of this module
Author = 'Reuben Miller'


# Company or vendor of this module
CompanyName = ''

# Copyright statement for this module
Copyright = '(c) 2020. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Cumulocity REST API'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = '2.0'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @(
    'format-data/alarms.ps1xml',
    'format-data/applicationReferences.ps1xml',
    'format-data/applications.ps1xml',
    'format-data/auditRecords.ps1xml',
    'format-data/events.ps1xml',
    'format-data/identity.ps1xml',
    'format-data/managedObjects.ps1xml',
    'format-data/managedObjectReferences.ps1xml',
    'format-data/measurements.ps1xml',
    'format-data/microservices.ps1xml',
    'format-data/operations.ps1xml',
    'format-data/options.ps1xml',
    'format-data/retentionRules.ps1xml',
    'format-data/roleReferences.ps1xml',
    'format-data/roles.ps1xml',
    'format-data/session.ps1xml',
    'format-data/tenants.ps1xml',
    'format-data/tenantStatistics.ps1xml',
    'format-data/userGroups.ps1xml',
    'format-data/users.ps1xml',
    'format-data/userReferences.ps1xml'
)

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = '*'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{
    PSData = @{
        #Prerelease of this module
        Prerelease = '-alpha07'

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @(
            'Cumulocity',
            'IoT',
            'REST-API',
            'Windows',
            'Linux',
            'MacOS',
            'PSEdition_Desktop',
            'PSEdition_Core'
        )

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        ProjectUri = 'https://reubenmiller.github.io/go-c8y'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

        # External dependent modules of this module
        # ExternalModuleDependencies = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
DefaultCommandPrefix = ''

}
