package usagestatistics

import (
	"context"
	"time"

	"github.com/reubenmiller/go-c8y/pkg/c8y/c8y_api/alternative/jsonmodels"
	"github.com/reubenmiller/go-c8y/pkg/c8y/c8y_api/alternative/op"
	"github.com/reubenmiller/go-c8y/pkg/c8y/c8y_api/core"
	"github.com/reubenmiller/go-c8y/pkg/c8y/c8y_api/pagination"
	"github.com/reubenmiller/go-c8y/pkg/c8y/c8y_api/types"
	"resty.dev/v3"
)

var ApiTenantStatisticsFiles = "/tenant/statistics/files"
var ApiTenantStatisticsFile = "/tenant/statistics/files/{id}"
var ApiTenantStatisticsFileLatestByMonth = "/tenant/statistics/files/latest/{month}"

const ParamId = "id"
const ParamChild = "child"

const ResultProperty = "statisticsFiles"

// Service
type Service core.Service

func NewService(common *core.Service) *Service {
	return (*Service)(common)
}

// ListOptions
type ListOptions struct {
	DateFrom time.Time `url:"dateFrom,omitempty,omitzero" layout:"2006-01-02"`

	DateTo time.Time `url:"dateTo,omitempty,omitzero" layout:"2006-01-02"`

	// Pagination options
	pagination.PaginationOptions
}

// UsageStatisticsFileIterator provides iteration over usage statistics files
type UsageStatisticsFileIterator = pagination.Iterator[jsonmodels.UsageStatisticsFile]

// List usage statistics summary files report metadata
func (s *Service) List(ctx context.Context, opt ListOptions) op.Result[jsonmodels.UsageStatisticsFile] {
	return core.ExecuteReturnCollection(ctx, s.ListB(opt), ResultProperty, types.ResponseFieldStatistics, jsonmodels.NewUsageStatisticsFile)
}

// ListAll returns an iterator for all usage statistics files
func (s *Service) ListAll(ctx context.Context, opts ListOptions) *UsageStatisticsFileIterator {
	if opts.PageSize == 0 {
		opts.PageSize = 2000
	}
	return pagination.Paginate(ctx, func(page int) op.Result[jsonmodels.UsageStatisticsFile] {
		opts.CurrentPage = page
		return s.List(ctx, opts)
	}, jsonmodels.NewUsageStatisticsFile, opts.GetMaxItems())
}

func (s *Service) ListB(opt ListOptions) *core.TryRequest {
	req := s.Client.R().
		SetMethod(resty.MethodGet).
		SetQueryParamsFromValues(core.QueryParameters(opt)).
		SetURL(ApiTenantStatisticsFiles)
	return core.NewTryRequest(s.Client, req, ResultProperty)
}

// Get a usage statistics file report
func (s *Service) Get(ctx context.Context, ID string) op.Result[jsonmodels.UsageStatisticsFile] {
	return core.ExecuteReturnResult(ctx, s.GetB(ID), jsonmodels.NewUsageStatisticsFile)
}

func (s *Service) GetB(ID string) *core.TryRequest {
	req := s.Client.R().
		SetMethod(resty.MethodGet).
		SetPathParam(ParamId, ID).
		SetURL(ApiTenantStatisticsFile)
	return core.NewTryRequest(s.Client, req)
}

type GetByMonthOptions struct {
	Month time.Time `url:"month,omitempty,omitzero" layout:"2006-01-02"`
}

// Get the latest statistics report for the given month
// Note: This is only accessible by the Management tenant
func (s *Service) GetByMonth(ctx context.Context, opt GetByMonthOptions) op.Result[jsonmodels.UsageStatisticsFile] {
	return core.ExecuteReturnResult(ctx, s.GetByMonthB(opt), jsonmodels.NewUsageStatisticsFile)
}

func (s *Service) GetByMonthB(opt GetByMonthOptions) *core.TryRequest {
	req := s.Client.R().
		SetMethod(resty.MethodGet).
		SetQueryParamsFromValues(core.QueryParameters(opt)).
		SetURL(ApiTenantStatisticsFileLatestByMonth)
	return core.NewTryRequest(s.Client, req)
}

// CreateOptions create options
type CreateOptions struct {
	DateFrom time.Time `url:"dateFrom,omitempty,omitzero"`

	DateTo time.Time `url:"dateTo,omitempty,omitzero"`
}

// Generate a TEST statistics file report for a given time range
// There are two types of statistics files:
//
// REAL - generated by the system on the first day of the month and including statistics from the previous month.
// TEST - generated by the user with a time range specified in the query parameters (dateFrom, dateTo).
func (s *Service) Create(ctx context.Context, opt ListOptions) op.Result[jsonmodels.UsageStatisticsFile] {
	return core.ExecuteReturnResult(ctx, s.CreateB(opt), jsonmodels.NewUsageStatisticsFile)
}

func (s *Service) CreateB(opt ListOptions) *core.TryRequest {
	req := s.Client.R().
		SetMethod(resty.MethodPost).
		SetQueryParamsFromValues(core.QueryParameters(opt)).
		SetHeader("Accept", types.MimeTypeApplicationJSON).
		SetURL(ApiTenantStatisticsFiles)
	return core.NewTryRequest(s.Client, req, "")
}
