// Code generated by tools/c8ygen; DO NOT EDIT.
//
// Source: docs/c8y-oas.yml
// Regenerate with: task generate  (or: go generate ./...)
//
// This file is the mechanical, 1:1-with-OAS substrate (Layer 0). The ergonomic
// public API (resolvers, option structs, upsert, iterators) is hand-written and
// lives outside this package. See docs/API_GEN.md.

package auditrecords

import (
	"time"

	"github.com/reubenmiller/go-c8y/v2/pkg/c8y/api/pagination"
)

// ListOptions to use when searching for audit records.
type ListOptions struct {
	// Name of the application from which the audit was carried out.
	Application string `url:"application,omitempty"`

	// Start date or date and time of the audit record (device time).
	DateFrom time.Time `url:"dateFrom,omitempty,omitzero"`

	// End date or date and time of the audit record (device time).
	DateTo time.Time `url:"dateTo,omitempty,omitzero"`

	// The platform component ID to which the audit is associated.
	Source string `url:"source,omitempty"`

	// The type of audit record to search for.
	Type string `url:"type,omitempty"`

	// The username to search for.
	User string `url:"user,omitempty"`

	// The following fields are not present in the OpenAPI spec
	// (declared via the overlay's extraFields). See docs/API_GEN.md.
	// If you are using a range query, setting revert=true sorts the results by
	// the oldest audit records first (default: newest first).
	// Note: not present in the OpenAPI spec; supported by the server.
	Revert bool `url:"revert,omitempty"`

	pagination.PaginationOptions
}
