// Code generated by tools/c8ygen; DO NOT EDIT.
//
// Source: docs/c8y-oas.yml
// Regenerate with: task generate  (or: go generate ./...)
//
// This file is the mechanical, 1:1-with-OAS substrate (Layer 0). The ergonomic
// public API (resolvers, option structs, upsert, iterators) is hand-written and
// lives outside this package. See docs/API_GEN.md.

package binaries

import (
	"github.com/reubenmiller/go-c8y/v2/pkg/c8y/api/pagination"
)

// ListOptions to use when searching for binaries.
type ListOptions struct {
	// Search for a specific child addition and list all the groups to which it belongs.
	ChildAdditionID string `url:"childAdditionId,omitempty"`

	// Search for a specific child asset and list all the groups to which it belongs.
	ChildAssetID string `url:"childAssetId,omitempty"`

	// Search for a specific child device and list all the groups to which it belongs.
	ChildDeviceID string `url:"childDeviceId,omitempty"`

	// The managed object IDs to search for.
	Ids []string `url:"ids,omitempty"`

	// Username of the owner of the managed objects.
	Owner string `url:"owner,omitempty"`

	// The type of managed object to search for.
	Type string `url:"type,omitempty"`

	pagination.PaginationOptions
}
