
---

information:
  name: applications
  description: Cumulocity applications
  descriptionLong: 'REST endpoint to interact with Cumulocity applications'
  link: https://cumulocity.com/guides/reference/applications/

endpoints:
  - name: getApplicationCollection
    description: 'Get collection of applications'
    method: GET
    path: /application/applications
    accept: application/vnd.com.nsn.cumulocity.applicationCollection+json
    alias:
        go: list
        powershell: Get-ApplicationCollection

  - name: newApplication
    description: 'New application'
    method: POST
    path: /application/applications
    accept: application/vnd.com.nsn.cumulocity.application+json
    alias:
        go: create
        powershell: New-Application

    body:
      - name: data
        type: json
        description: data

      - name: name
        type: string
        required: false
        description: Name of application

      - name: key
        type: string
        required: false
        description: 	Shared secret of application

      - name: type
        type: string
        validationSet: [EXTERNAL, HOSTED, MICROSERVICE]
        required: false
        description: Type of application. Possible values are EXTERNAL, HOSTED, MICROSERVICE

      - name: availability
        type: string
        validationSet: [MARKET, PRIVATE]
        required: false
        description: Application will be applied to this type of documents, possible values [ALARM, AUDIT, EVENT, MEASUREMENT, OPERATION, *].

      - name: contextPath
        type: string
        required: false
        description: contextPath of the hosted application. Required when application type is HOSTED

      - name: resourcesUrl
        type: string
        required: false
        description: URL to application base directory hosted on an external server. Required when application type is HOSTED

      - name: resourcesUsername
        type: string
        required: false
        description: authorization username to access resourcesUrl

      - name: resourcesPassword
        type: string
        required: false
        description: authorization password to access resourcesUrl

      - name: externalUrl
        type: string
        required: false
        description: URL to the external application. Required when application type is EXTERNAL

  - name: copyApplication
    description: 'Copy application'
    descriptionLong: >
      A POST request to the 'clone' resource creates a new application based on an already existing one.

      The properties are copied to the newly created application. For name, key and context path a 'clone' prefix is added in order to be unique.

      If the target application is hosted and has an active version, the new application will have the active version with the same content.

      The response contains a representation of the newly created application.

      Required role ROLE_APPLICATION_MANAGMENT_ADMIN
    method: POST
    path: /application/applications/{id}/clone
    accept: application/vnd.com.nsn.cumulocity.application+json
    alias:
        go: copy
        powershell: Copy-Application
    pathParameters:
      - name: id
        type: string
        required: true
        description: Application id

  - name: getApplication
    description: 'Get application'
    method: GET
    path: /application/applications/{id}
    accept: application/vnd.com.nsn.cumulocity.application+json
    alias:
        go: get
        powershell: Get-Application
    pathParameters:
      - name: id
        type: string
        required: true
        description: Application id

  - name: deleteApplication
    description: 'Delete application'
    descriptionLong: 'Info: The application can only be removed when its availability is PRIVATE or in other case when it has no subscriptions.'
    method: DELETE
    path: /application/applications/{id}
    alias:
        go: delete
        powershell: Remove-Application
    pathParameters:
      - name: id
        type: string
        required: true
        description: Application id

  - name: updateApplication
    description: 'Update application'
    method: PUT
    path: /application/applications/{id}
    accept: application/vnd.com.nsn.cumulocity.application+json
    alias:
        go: updateBinary
        powershell: Update-Binary
    pathParameters:
      - name: id
        type: string
        required: true
        description: Application id

    body:
      - name: data
        type: json
        description: data

      - name: name
        type: string
        required: false
        description: Name of application

      - name: key
        type: string
        required: false
        description: 	Shared secret of application

      - name: availability
        type: string
        validationSet: [MARKET, PRIVATE]
        required: false
        description: Application will be applied to this type of documents, possible values [ALARM, AUDIT, EVENT, MEASUREMENT, OPERATION, *].

      - name: contextPath
        type: string
        required: false
        description: contextPath of the hosted application

      - name: resourcesUrl
        type: string
        required: false
        description: URL to application base directory hosted on an external server

      - name: resourcesUsername
        type: string
        required: false
        description: authorization username to access resourcesUrl

      - name: resourcesPassword
        type: string
        required: false
        description: authorization password to access resourcesUrl

      - name: externalUrl
        type: string
        required: false
        description: URL to the external application


  - name: newApplicationBinary
    description: 'New application binary'
    description: >
      For the applications of type 'microservice' and 'web application' to be available for Cumulocity platform users, a binary zip file must be uploaded.

      For the microservice application, the zip file must consist of
        * cumulocity.json - file describing the deployment
        * image.tar - executable docker image

      For the web application, the zip file must include index.html in the root directory.

    method: POST
    path: /application/applications/{id}/binaries
    accept: application/vnd.com.nsn.cumulocity.application+json
    alias:
        go: createBinary
        powershell: New-ApplicationBinary
    pathParameters:
      - name: id
        type: string
        required: true
        description: Application id
    body:
      - name: file
        type: file
        required: true
        description: File to be uploaded as a binary

  - name: getApplicationBootstrapUser
    description: 'Get application bootstrap user'
    method: GET
    path: /application/applications/{id}/bootstrapUser
    accept: application/vnd.com.nsn.cumulocity.user+json
    alias:
        go: getBootstrapUser
        powershell: Get-ApplicationBootstrapUser
    pathParameters:
      - name: id
        type: string
        required: true
        description: Application id
