// Code generated by tools/c8ygen; DO NOT EDIT.
//
// Source: docs/c8y-oas.yml
// Regenerate with: task generate  (or: go generate ./...)
//
// This file is the mechanical, 1:1-with-OAS substrate (Layer 0). The ergonomic
// public API (resolvers, option structs, upsert, iterators) is hand-written and
// lives outside this package. See docs/API_GEN.md.

package tenants

import (
	"github.com/reubenmiller/go-c8y/v2/pkg/c8y/api/pagination"
)

// ListOptions to use when searching for tenants.
type ListOptions struct {
	// Company name associated with the Cumulocity tenant.
	Company string `url:"company,omitempty"`

	// Domain name of the Cumulocity tenant.
	Domain string `url:"domain,omitempty"`

	// Identifier of the Cumulocity tenant's parent. Works only for requests sent with management tenant credentials.
	Parent string `url:"parent,omitempty"`

	pagination.PaginationOptions
}
