// Code generated by tools/c8ygen; DO NOT EDIT.
//
// Source: docs/c8y-oas.yml
// Regenerate with: task generate  (or: go generate ./...)
//
// This file is the mechanical, 1:1-with-OAS substrate (Layer 0). The ergonomic
// public API (resolvers, option structs, upsert, iterators) is hand-written and
// lives outside this package. See docs/API_GEN.md.

package loginoptions

import (
	"github.com/reubenmiller/go-c8y/v2/pkg/c8y/api/pagination"
)

// ListOptions to filter the login options by.
type ListOptions struct {
	// If this is set to `true`, the management tenant login options will be returned.
	Management bool `url:"management,omitempty"`

	// Unique identifier of a Cumulocity tenant.
	TenantID string `url:"tenantId,omitempty"`

	pagination.PaginationOptions
}
