// Code generated by tools/c8ygen; DO NOT EDIT.
//
// Source: docs/c8y-oas.yml
// Regenerate with: task generate  (or: go generate ./...)
//
// This file is the mechanical, 1:1-with-OAS substrate (Layer 0). The ergonomic
// public API (resolvers, option structs, upsert, iterators) is hand-written and
// lives outside this package. See docs/API_GEN.md.

package spec

// Enum value constants derived from the OpenAPI schema definitions.

// AlarmSeverity enumerates the values for the AlarmSeverity field.
type AlarmSeverity = string

const (
	AlarmSeverityCritical AlarmSeverity = "CRITICAL"
	AlarmSeverityMajor    AlarmSeverity = "MAJOR"
	AlarmSeverityMinor    AlarmSeverity = "MINOR"
	AlarmSeverityWarning  AlarmSeverity = "WARNING"
)

// AlarmStatus enumerates the values for the AlarmStatus field.
type AlarmStatus = string

const (
	AlarmStatusActive       AlarmStatus = "ACTIVE"
	AlarmStatusAcknowledged AlarmStatus = "ACKNOWLEDGED"
	AlarmStatusCleared      AlarmStatus = "CLEARED"
)

// AlarmUpsertSeverity enumerates the values for the AlarmUpsertSeverity field.
type AlarmUpsertSeverity = string

const (
	AlarmUpsertSeverityCritical AlarmUpsertSeverity = "CRITICAL"
	AlarmUpsertSeverityMajor    AlarmUpsertSeverity = "MAJOR"
	AlarmUpsertSeverityMinor    AlarmUpsertSeverity = "MINOR"
	AlarmUpsertSeverityWarning  AlarmUpsertSeverity = "WARNING"
)

// AlarmUpsertStatus enumerates the values for the AlarmUpsertStatus field.
type AlarmUpsertStatus = string

const (
	AlarmUpsertStatusActive       AlarmUpsertStatus = "ACTIVE"
	AlarmUpsertStatusAcknowledged AlarmUpsertStatus = "ACKNOWLEDGED"
	AlarmUpsertStatusCleared      AlarmUpsertStatus = "CLEARED"
)

// ApplicationAvailability enumerates the values for the ApplicationAvailability field.
type ApplicationAvailability = string

const (
	ApplicationAvailabilityMarket  ApplicationAvailability = "MARKET"
	ApplicationAvailabilityPrivate ApplicationAvailability = "PRIVATE"
)

// ApplicationNoMicroserviceManifestAvailability enumerates the values for the ApplicationNoMicroserviceManifestAvailability field.
type ApplicationNoMicroserviceManifestAvailability = string

const (
	ApplicationNoMicroserviceManifestAvailabilityMarket  ApplicationNoMicroserviceManifestAvailability = "MARKET"
	ApplicationNoMicroserviceManifestAvailabilityPrivate ApplicationNoMicroserviceManifestAvailability = "PRIVATE"
)

// ApplicationNoMicroserviceManifestType enumerates the values for the ApplicationNoMicroserviceManifestType field.
type ApplicationNoMicroserviceManifestType = string

const (
	ApplicationNoMicroserviceManifestTypeExternal     ApplicationNoMicroserviceManifestType = "EXTERNAL"
	ApplicationNoMicroserviceManifestTypeHosted       ApplicationNoMicroserviceManifestType = "HOSTED"
	ApplicationNoMicroserviceManifestTypeMicroservice ApplicationNoMicroserviceManifestType = "MICROSERVICE"
)

// ApplicationType enumerates the values for the ApplicationType field.
type ApplicationType = string

const (
	ApplicationTypeExternal     ApplicationType = "EXTERNAL"
	ApplicationTypeHosted       ApplicationType = "HOSTED"
	ApplicationTypeMicroservice ApplicationType = "MICROSERVICE"
)

// AuditRecordC8yMetadataAction enumerates the values for the AuditRecordC8yMetadataAction field.
type AuditRecordC8yMetadataAction = string

const (
	AuditRecordC8yMetadataActionSubscribe AuditRecordC8yMetadataAction = "SUBSCRIBE"
	AuditRecordC8yMetadataActionDeploy    AuditRecordC8yMetadataAction = "DEPLOY"
	AuditRecordC8yMetadataActionScale     AuditRecordC8yMetadataAction = "SCALE"
	AuditRecordC8yMetadataActionDelete    AuditRecordC8yMetadataAction = "DELETE"
)

// AuditRecordChangesItemChangeType enumerates the values for the AuditRecordChangesItemChangeType field.
type AuditRecordChangesItemChangeType = string

const (
	AuditRecordChangesItemChangeTypeAdded    AuditRecordChangesItemChangeType = "ADDED"
	AuditRecordChangesItemChangeTypeReplaced AuditRecordChangesItemChangeType = "REPLACED"
)

// AuditRecordSeverity enumerates the values for the AuditRecordSeverity field.
type AuditRecordSeverity = string

const (
	AuditRecordSeverityCritical    AuditRecordSeverity = "CRITICAL"
	AuditRecordSeverityMajor       AuditRecordSeverity = "MAJOR"
	AuditRecordSeverityMinor       AuditRecordSeverity = "MINOR"
	AuditRecordSeverityWarning     AuditRecordSeverity = "WARNING"
	AuditRecordSeverityInformation AuditRecordSeverity = "INFORMATION"
)

// AuditRecordType enumerates the values for the AuditRecordType field.
type AuditRecordType = string

const (
	AuditRecordTypeAlarm               AuditRecordType = "Alarm"
	AuditRecordTypeApplication         AuditRecordType = "Application"
	AuditRecordTypeBulkOperation       AuditRecordType = "BulkOperation"
	AuditRecordTypeCepModule           AuditRecordType = "CepModule"
	AuditRecordTypeConnector           AuditRecordType = "Connector"
	AuditRecordTypeEvent               AuditRecordType = "Event"
	AuditRecordTypeGroup               AuditRecordType = "Group"
	AuditRecordTypeInventory           AuditRecordType = "Inventory"
	AuditRecordTypeInventoryRole       AuditRecordType = "InventoryRole"
	AuditRecordTypeOperation           AuditRecordType = "Operation"
	AuditRecordTypeOption              AuditRecordType = "Option"
	AuditRecordTypeReport              AuditRecordType = "Report"
	AuditRecordTypeSingleSignOn        AuditRecordType = "SingleSignOn"
	AuditRecordTypeSmartRule           AuditRecordType = "SmartRule"
	AuditRecordTypeSystem              AuditRecordType = "SYSTEM"
	AuditRecordTypeTenant              AuditRecordType = "Tenant"
	AuditRecordTypeTenantAuthConfig    AuditRecordType = "TenantAuthConfig"
	AuditRecordTypeTrustedCertificates AuditRecordType = "TrustedCertificates"
	AuditRecordTypeUser                AuditRecordType = "User"
	AuditRecordTypeUserAuthentication  AuditRecordType = "UserAuthentication"
)

// AuthConfigExternalTokenConfigValidationMethod enumerates the values for the AuthConfigExternalTokenConfigValidationMethod field.
type AuthConfigExternalTokenConfigValidationMethod = string

const (
	AuthConfigExternalTokenConfigValidationMethodIntrospection AuthConfigExternalTokenConfigValidationMethod = "INTROSPECTION"
	AuthConfigExternalTokenConfigValidationMethodUserinfo      AuthConfigExternalTokenConfigValidationMethod = "USERINFO"
)

// AuthConfigGrantType enumerates the values for the AuthConfigGrantType field.
type AuthConfigGrantType = string

const (
	AuthConfigGrantTypeAuthorizationCode AuthConfigGrantType = "AUTHORIZATION_CODE"
	AuthConfigGrantTypePassword          AuthConfigGrantType = "PASSWORD"
)

// AuthConfigSignatureVerificationConfigManualCertificatesAlg enumerates the values for the AuthConfigSignatureVerificationConfigManualCertificatesAlg field.
type AuthConfigSignatureVerificationConfigManualCertificatesAlg = string

const (
	AuthConfigSignatureVerificationConfigManualCertificatesAlgRsa  AuthConfigSignatureVerificationConfigManualCertificatesAlg = "RSA"
	AuthConfigSignatureVerificationConfigManualCertificatesAlgPcks AuthConfigSignatureVerificationConfigManualCertificatesAlg = "PCKS"
)

// AuthConfigType enumerates the values for the AuthConfigType field.
type AuthConfigType = string

const (
	AuthConfigTypeBasic          AuthConfigType = "BASIC"
	AuthConfigTypeOauth2         AuthConfigType = "OAUTH2"
	AuthConfigTypeOauth2Internal AuthConfigType = "OAUTH2_INTERNAL"
)

// AuthConfigUserManagementSource enumerates the values for the AuthConfigUserManagementSource field.
type AuthConfigUserManagementSource = string

const (
	AuthConfigUserManagementSourceInternal AuthConfigUserManagementSource = "INTERNAL"
	AuthConfigUserManagementSourceRemote   AuthConfigUserManagementSource = "REMOTE"
)

// BulkNewDeviceRequestCredentialUpdatedListItemBulkNewDeviceStatus enumerates the values for the BulkNewDeviceRequestCredentialUpdatedListItemBulkNewDeviceStatus field.
type BulkNewDeviceRequestCredentialUpdatedListItemBulkNewDeviceStatus = string

const (
	BulkNewDeviceRequestCredentialUpdatedListItemBulkNewDeviceStatusCreated           BulkNewDeviceRequestCredentialUpdatedListItemBulkNewDeviceStatus = "CREATED"
	BulkNewDeviceRequestCredentialUpdatedListItemBulkNewDeviceStatusFailed            BulkNewDeviceRequestCredentialUpdatedListItemBulkNewDeviceStatus = "FAILED"
	BulkNewDeviceRequestCredentialUpdatedListItemBulkNewDeviceStatusCredentialUpdated BulkNewDeviceRequestCredentialUpdatedListItemBulkNewDeviceStatus = "CREDENTIAL_UPDATED"
)

// BulkNewDeviceRequestFailedCreationListItemBulkNewDeviceStatus enumerates the values for the BulkNewDeviceRequestFailedCreationListItemBulkNewDeviceStatus field.
type BulkNewDeviceRequestFailedCreationListItemBulkNewDeviceStatus = string

const (
	BulkNewDeviceRequestFailedCreationListItemBulkNewDeviceStatusCreated           BulkNewDeviceRequestFailedCreationListItemBulkNewDeviceStatus = "CREATED"
	BulkNewDeviceRequestFailedCreationListItemBulkNewDeviceStatusFailed            BulkNewDeviceRequestFailedCreationListItemBulkNewDeviceStatus = "FAILED"
	BulkNewDeviceRequestFailedCreationListItemBulkNewDeviceStatusCredentialUpdated BulkNewDeviceRequestFailedCreationListItemBulkNewDeviceStatus = "CREDENTIAL_UPDATED"
)

// BulkOperationGeneralStatus enumerates the values for the BulkOperationGeneralStatus field.
type BulkOperationGeneralStatus = string

const (
	BulkOperationGeneralStatusScheduled           BulkOperationGeneralStatus = "SCHEDULED"
	BulkOperationGeneralStatusExecuting           BulkOperationGeneralStatus = "EXECUTING"
	BulkOperationGeneralStatusExecutingWithErrors BulkOperationGeneralStatus = "EXECUTING_WITH_ERRORS"
	BulkOperationGeneralStatusSuccessful          BulkOperationGeneralStatus = "SUCCESSFUL"
	BulkOperationGeneralStatusFailed              BulkOperationGeneralStatus = "FAILED"
	BulkOperationGeneralStatusCanceled            BulkOperationGeneralStatus = "CANCELED"
)

// BulkOperationStatus enumerates the values for the BulkOperationStatus field.
type BulkOperationStatus = string

const (
	BulkOperationStatusActive     BulkOperationStatus = "ACTIVE"
	BulkOperationStatusInProgress BulkOperationStatus = "IN_PROGRESS"
	BulkOperationStatusCompleted  BulkOperationStatus = "COMPLETED"
	BulkOperationStatusDeleted    BulkOperationStatus = "DELETED"
)

// C8yAvailabilityConnectionStatus enumerates the values for the C8yAvailabilityConnectionStatus field.
type C8yAvailabilityConnectionStatus = string

const (
	C8yAvailabilityConnectionStatusConnected    C8yAvailabilityConnectionStatus = "CONNECTED"
	C8yAvailabilityConnectionStatusDisconnected C8yAvailabilityConnectionStatus = "DISCONNECTED"
	C8yAvailabilityConnectionStatusMaintenance  C8yAvailabilityConnectionStatus = "MAINTENANCE"
)

// C8yAvailabilityDataStatus enumerates the values for the C8yAvailabilityDataStatus field.
type C8yAvailabilityDataStatus = string

const (
	C8yAvailabilityDataStatusAvailable   C8yAvailabilityDataStatus = "AVAILABLE"
	C8yAvailabilityDataStatusMaintenance C8yAvailabilityDataStatus = "MAINTENANCE"
	C8yAvailabilityDataStatusUnavailable C8yAvailabilityDataStatus = "UNAVAILABLE"
)

// FeatureTogglePhase enumerates the values for the FeatureTogglePhase field.
type FeatureTogglePhase = string

const (
	FeatureTogglePhaseInDevelopment      FeatureTogglePhase = "IN_DEVELOPMENT"
	FeatureTogglePhasePrivatePreview     FeatureTogglePhase = "PRIVATE_PREVIEW"
	FeatureTogglePhasePublicPreview      FeatureTogglePhase = "PUBLIC_PREVIEW"
	FeatureTogglePhaseGenerallyAvailable FeatureTogglePhase = "GENERALLY_AVAILABLE"
)

// FeatureToggleStrategy enumerates the values for the FeatureToggleStrategy field.
type FeatureToggleStrategy = string

const (
	FeatureToggleStrategyDefault FeatureToggleStrategy = "DEFAULT"
	FeatureToggleStrategyTenant  FeatureToggleStrategy = "TENANT"
)

// InventoryRolePermissionPermission enumerates the values for the InventoryRolePermissionPermission field.
type InventoryRolePermissionPermission = string

const (
	InventoryRolePermissionPermissionAdmin InventoryRolePermissionPermission = "ADMIN"
	InventoryRolePermissionPermissionRead  InventoryRolePermissionPermission = "READ"
	InventoryRolePermissionPermissionEmpty InventoryRolePermissionPermission = "*"
)

// InventoryRolePermissionScope enumerates the values for the InventoryRolePermissionScope field.
type InventoryRolePermissionScope = string

const (
	InventoryRolePermissionScopeAlarm         InventoryRolePermissionScope = "ALARM"
	InventoryRolePermissionScopeAudit         InventoryRolePermissionScope = "AUDIT"
	InventoryRolePermissionScopeEvent         InventoryRolePermissionScope = "EVENT"
	InventoryRolePermissionScopeManagedObject InventoryRolePermissionScope = "MANAGED_OBJECT"
	InventoryRolePermissionScopeMeasurement   InventoryRolePermissionScope = "MEASUREMENT"
	InventoryRolePermissionScopeOperation     InventoryRolePermissionScope = "OPERATION"
	InventoryRolePermissionScopeEmpty         InventoryRolePermissionScope = "*"
)

// JSONPredicateRepresentationOperator enumerates the values for the JSONPredicateRepresentationOperator field.
type JSONPredicateRepresentationOperator = string

const (
	JSONPredicateRepresentationOperatorEq  JSONPredicateRepresentationOperator = "EQ"
	JSONPredicateRepresentationOperatorNeq JSONPredicateRepresentationOperator = "NEQ"
	JSONPredicateRepresentationOperatorGt  JSONPredicateRepresentationOperator = "GT"
	JSONPredicateRepresentationOperatorLt  JSONPredicateRepresentationOperator = "LT"
	JSONPredicateRepresentationOperatorGte JSONPredicateRepresentationOperator = "GTE"
	JSONPredicateRepresentationOperatorLte JSONPredicateRepresentationOperator = "LTE"
	JSONPredicateRepresentationOperatorIn  JSONPredicateRepresentationOperator = "IN"
	JSONPredicateRepresentationOperatorAnd JSONPredicateRepresentationOperator = "AND"
	JSONPredicateRepresentationOperatorOr  JSONPredicateRepresentationOperator = "OR"
)

// LoginFormGrantType enumerates the values for the LoginFormGrantType field.
type LoginFormGrantType = string

const (
	LoginFormGrantTypePassword          LoginFormGrantType = "PASSWORD"
	LoginFormGrantTypeAuthorizationCode LoginFormGrantType = "AUTHORIZATION_CODE"
)

// LoginOptionGrantType enumerates the values for the LoginOptionGrantType field.
type LoginOptionGrantType = string

const (
	LoginOptionGrantTypePassword          LoginOptionGrantType = "PASSWORD"
	LoginOptionGrantTypeAuthorizationCode LoginOptionGrantType = "AUTHORIZATION_CODE"
)

// MicroserviceApplicationManifestBillingMode enumerates the values for the MicroserviceApplicationManifestBillingMode field.
type MicroserviceApplicationManifestBillingMode = string

const (
	MicroserviceApplicationManifestBillingModeResources    MicroserviceApplicationManifestBillingMode = "RESOURCES"
	MicroserviceApplicationManifestBillingModeSubscription MicroserviceApplicationManifestBillingMode = "SUBSCRIPTION"
)

// MicroserviceApplicationManifestIsolation enumerates the values for the MicroserviceApplicationManifestIsolation field.
type MicroserviceApplicationManifestIsolation = string

const (
	MicroserviceApplicationManifestIsolationMultiTenant MicroserviceApplicationManifestIsolation = "MULTI_TENANT"
	MicroserviceApplicationManifestIsolationPerTenant   MicroserviceApplicationManifestIsolation = "PER_TENANT"
)

// MicroserviceApplicationManifestScale enumerates the values for the MicroserviceApplicationManifestScale field.
type MicroserviceApplicationManifestScale = string

const (
	MicroserviceApplicationManifestScaleNone MicroserviceApplicationManifestScale = "NONE"
	MicroserviceApplicationManifestScaleAuto MicroserviceApplicationManifestScale = "AUTO"
)

// NewDeviceRequestStatus enumerates the values for the NewDeviceRequestStatus field.
type NewDeviceRequestStatus = string

const (
	NewDeviceRequestStatusWaitingForConnection NewDeviceRequestStatus = "WAITING_FOR_CONNECTION"
	NewDeviceRequestStatusPendingAcceptance    NewDeviceRequestStatus = "PENDING_ACCEPTANCE"
	NewDeviceRequestStatusAccepted             NewDeviceRequestStatus = "ACCEPTED"
)

// NotificationSubscriptionContext enumerates the values for the NotificationSubscriptionContext field.
type NotificationSubscriptionContext = string

const (
	NotificationSubscriptionContextMo     NotificationSubscriptionContext = "mo"
	NotificationSubscriptionContextTenant NotificationSubscriptionContext = "tenant"
)

// NotificationSubscriptionResultResult enumerates the values for the NotificationSubscriptionResultResult field.
type NotificationSubscriptionResultResult = string

const (
	NotificationSubscriptionResultResultDone      NotificationSubscriptionResultResult = "DONE"
	NotificationSubscriptionResultResultScheduled NotificationSubscriptionResultResult = "SCHEDULED"
)

// NotificationSubscriptionSubscriptionFilterApisItem enumerates the values for the NotificationSubscriptionSubscriptionFilterApisItem field.
type NotificationSubscriptionSubscriptionFilterApisItem = string

const (
	NotificationSubscriptionSubscriptionFilterApisItemAlarms             NotificationSubscriptionSubscriptionFilterApisItem = "alarms"
	NotificationSubscriptionSubscriptionFilterApisItemAlarmsWithChildren NotificationSubscriptionSubscriptionFilterApisItem = "alarmsWithChildren"
	NotificationSubscriptionSubscriptionFilterApisItemEvents             NotificationSubscriptionSubscriptionFilterApisItem = "events"
	NotificationSubscriptionSubscriptionFilterApisItemEventsWithChildren NotificationSubscriptionSubscriptionFilterApisItem = "eventsWithChildren"
	NotificationSubscriptionSubscriptionFilterApisItemManagedobjects     NotificationSubscriptionSubscriptionFilterApisItem = "managedobjects"
	NotificationSubscriptionSubscriptionFilterApisItemMeasurements       NotificationSubscriptionSubscriptionFilterApisItem = "measurements"
	NotificationSubscriptionSubscriptionFilterApisItemOperations         NotificationSubscriptionSubscriptionFilterApisItem = "operations"
	NotificationSubscriptionSubscriptionFilterApisItemEmpty              NotificationSubscriptionSubscriptionFilterApisItem = "*"
)

// NotificationTokenClaimsType enumerates the values for the NotificationTokenClaimsType field.
type NotificationTokenClaimsType = string

const (
	NotificationTokenClaimsTypeNotification NotificationTokenClaimsType = "notification"
)

// OperationStatus enumerates the values for the OperationStatus field.
type OperationStatus = string

const (
	OperationStatusSuccessful OperationStatus = "SUCCESSFUL"
	OperationStatusFailed     OperationStatus = "FAILED"
	OperationStatusExecuting  OperationStatus = "EXECUTING"
	OperationStatusPending    OperationStatus = "PENDING"
)

// RealtimeNotificationChannel enumerates the values for the RealtimeNotificationChannel field.
type RealtimeNotificationChannel = string

const (
	RealtimeNotificationChannelMetaHandshake   RealtimeNotificationChannel = "/meta/handshake"
	RealtimeNotificationChannelMetaSubscribe   RealtimeNotificationChannel = "/meta/subscribe"
	RealtimeNotificationChannelMetaUnsubscribe RealtimeNotificationChannel = "/meta/unsubscribe"
	RealtimeNotificationChannelMetaConnect     RealtimeNotificationChannel = "/meta/connect"
	RealtimeNotificationChannelMetaDisconnect  RealtimeNotificationChannel = "/meta/disconnect"
)

// RealtimeNotificationExtSystemOfUnits enumerates the values for the RealtimeNotificationExtSystemOfUnits field.
type RealtimeNotificationExtSystemOfUnits = string

const (
	RealtimeNotificationExtSystemOfUnitsImperial RealtimeNotificationExtSystemOfUnits = "imperial"
	RealtimeNotificationExtSystemOfUnitsMetric   RealtimeNotificationExtSystemOfUnits = "metric"
)

// RequestRepresentationMethod enumerates the values for the RequestRepresentationMethod field.
type RequestRepresentationMethod = string

const (
	RequestRepresentationMethodGet  RequestRepresentationMethod = "GET"
	RequestRepresentationMethodPost RequestRepresentationMethod = "POST"
)

// RequestRepresentationOperation enumerates the values for the RequestRepresentationOperation field.
type RequestRepresentationOperation = string

const (
	RequestRepresentationOperationExecute  RequestRepresentationOperation = "EXECUTE"
	RequestRepresentationOperationRedirect RequestRepresentationOperation = "REDIRECT"
)

// RetentionRuleDataType enumerates the values for the RetentionRuleDataType field.
type RetentionRuleDataType = string

const (
	RetentionRuleDataTypeAlarm         RetentionRuleDataType = "ALARM"
	RetentionRuleDataTypeAudit         RetentionRuleDataType = "AUDIT"
	RetentionRuleDataTypeBulkOperation RetentionRuleDataType = "BULK_OPERATION"
	RetentionRuleDataTypeEvent         RetentionRuleDataType = "EVENT"
	RetentionRuleDataTypeMeasurement   RetentionRuleDataType = "MEASUREMENT"
	RetentionRuleDataTypeOperation     RetentionRuleDataType = "OPERATION"
	RetentionRuleDataTypeEmpty         RetentionRuleDataType = "*"
)

// StatisticsFileType enumerates the values for the StatisticsFileType field.
type StatisticsFileType = string

const (
	StatisticsFileTypeReal StatisticsFileType = "REAL"
	StatisticsFileTypeTest StatisticsFileType = "TEST"
)

// TenantStatus enumerates the values for the TenantStatus field.
type TenantStatus = string

const (
	TenantStatusActive    TenantStatus = "ACTIVE"
	TenantStatusSuspended TenantStatus = "SUSPENDED"
)

// TenantTFADataStrategy enumerates the values for the TenantTFADataStrategy field.
type TenantTFADataStrategy = string

const (
	TenantTFADataStrategySms  TenantTFADataStrategy = "SMS"
	TenantTFADataStrategyTOTP TenantTFADataStrategy = "TOTP"
)

// TenantTFAStrategyStrategy enumerates the values for the TenantTFAStrategyStrategy field.
type TenantTFAStrategyStrategy = string

const (
	TenantTFAStrategyStrategySms  TenantTFAStrategyStrategy = "SMS"
	TenantTFAStrategyStrategyTOTP TenantTFAStrategyStrategy = "TOTP"
)

// TrustedCertificateStatus enumerates the values for the TrustedCertificateStatus field.
type TrustedCertificateStatus = string

const (
	TrustedCertificateStatusEnabled  TrustedCertificateStatus = "ENABLED"
	TrustedCertificateStatusDisabled TrustedCertificateStatus = "DISABLED"
)

// UploadedTrustedCertificateStatus enumerates the values for the UploadedTrustedCertificateStatus field.
type UploadedTrustedCertificateStatus = string

const (
	UploadedTrustedCertificateStatusEnabled  UploadedTrustedCertificateStatus = "ENABLED"
	UploadedTrustedCertificateStatusDisabled UploadedTrustedCertificateStatus = "DISABLED"
)

// UserPasswordStrength enumerates the values for the UserPasswordStrength field.
type UserPasswordStrength = string

const (
	UserPasswordStrengthGreen  UserPasswordStrength = "GREEN"
	UserPasswordStrengthYellow UserPasswordStrength = "YELLOW"
	UserPasswordStrengthRed    UserPasswordStrength = "RED"
)

// UserTFADataStrategy enumerates the values for the UserTFADataStrategy field.
type UserTFADataStrategy = string

const (
	UserTFADataStrategySms  UserTFADataStrategy = "SMS"
	UserTFADataStrategyTOTP UserTFADataStrategy = "TOTP"
)
