// Code generated by tools/c8ygen; DO NOT EDIT.
//
// Source: docs/c8y-oas.yml
// Regenerate with: task generate  (or: go generate ./...)
//
// This file is the mechanical, 1:1-with-OAS substrate (Layer 0). The ergonomic
// public API (resolvers, option structs, upsert, iterators) is hand-written and
// lives outside this package. See docs/API_GEN.md.

package spec

// Path constants for Cumulocity REST API endpoints.
// Placeholders ({id}, {childId}, ...) are filled at request time via SetPathParam.
const (
	// WellKnownESTSimpleenroll — POST
	WellKnownESTSimpleenroll = "/.well-known/est/simpleenroll"
	// WellKnownESTSimplereenroll — POST
	WellKnownESTSimplereenroll = "/.well-known/est/simplereenroll"
	// Alarm — GET
	Alarm = "/alarm"
	// AlarmAlarms — GET PUT POST DELETE
	AlarmAlarms = "/alarm/alarms"
	// AlarmAlarmsCount — GET
	AlarmAlarmsCount = "/alarm/alarms/count"
	// AlarmAlarmsUpsert — POST
	AlarmAlarmsUpsert = "/alarm/alarms/upsert"
	// AlarmAlarmsID — GET PUT
	AlarmAlarmsID = "/alarm/alarms/{id}"
	// Application — GET
	Application = "/application"
	// ApplicationApplications — GET POST
	ApplicationApplications = "/application/applications"
	// ApplicationApplicationsID — GET PUT DELETE
	ApplicationApplicationsID = "/application/applications/{id}"
	// ApplicationApplicationsIDBinaries — GET POST
	ApplicationApplicationsIDBinaries = "/application/applications/{id}/binaries"
	// ApplicationApplicationsIDBinariesBinaryID — GET DELETE
	ApplicationApplicationsIDBinariesBinaryID = "/application/applications/{id}/binaries/{binaryId}"
	// ApplicationApplicationsIDBootstrapUser — GET
	ApplicationApplicationsIDBootstrapUser = "/application/applications/{id}/bootstrapUser"
	// ApplicationApplicationsIDClone — POST
	ApplicationApplicationsIDClone = "/application/applications/{id}/clone"
	// ApplicationApplicationsIDVersions — GET POST DELETE
	ApplicationApplicationsIDVersions = "/application/applications/{id}/versions"
	// ApplicationApplicationsIDVersionsVersion — PUT
	ApplicationApplicationsIDVersionsVersion = "/application/applications/{id}/versions/{version}"
	// ApplicationApplicationsIDVersionsVersion10 — GET
	ApplicationApplicationsIDVersionsVersion10 = "/application/applications/{id}/versions?version=1.0"
	// ApplicationApplicationsByNameName — GET
	ApplicationApplicationsByNameName = "/application/applicationsByName/{name}"
	// ApplicationApplicationsByOwnerTenantID — GET
	ApplicationApplicationsByOwnerTenantID = "/application/applicationsByOwner/{tenantId}"
	// ApplicationApplicationsByTenantTenantID — GET
	ApplicationApplicationsByTenantTenantID = "/application/applicationsByTenant/{tenantId}"
	// ApplicationApplicationsByUserUsername — GET
	ApplicationApplicationsByUserUsername = "/application/applicationsByUser/{username}"
	// ApplicationCurrentApplication — GET PUT
	ApplicationCurrentApplication = "/application/currentApplication"
	// ApplicationCurrentApplicationSettings — GET
	ApplicationCurrentApplicationSettings = "/application/currentApplication/settings"
	// ApplicationCurrentApplicationSubscriptions — GET
	ApplicationCurrentApplicationSubscriptions = "/application/currentApplication/subscriptions"
	// Audit — GET
	Audit = "/audit"
	// AuditAuditRecords — GET POST
	AuditAuditRecords = "/audit/auditRecords"
	// AuditAuditRecordsID — GET
	AuditAuditRecordsID = "/audit/auditRecords/{id}"
	// CertificateAuthority — POST
	CertificateAuthority = "/certificate-authority"
	// CertificateAuthorityRenew — POST
	CertificateAuthorityRenew = "/certificate-authority/renew"
	// Devicecontrol — GET
	Devicecontrol = "/devicecontrol"
	// DevicecontrolBulkNewDeviceRequests — POST
	DevicecontrolBulkNewDeviceRequests = "/devicecontrol/bulkNewDeviceRequests"
	// DevicecontrolBulkoperations — GET POST
	DevicecontrolBulkoperations = "/devicecontrol/bulkoperations"
	// DevicecontrolBulkoperationsID — GET PUT DELETE
	DevicecontrolBulkoperationsID = "/devicecontrol/bulkoperations/{id}"
	// DevicecontrolDeviceAccessToken — POST
	DevicecontrolDeviceAccessToken = "/devicecontrol/deviceAccessToken"
	// DevicecontrolDeviceCredentials — POST
	DevicecontrolDeviceCredentials = "/devicecontrol/deviceCredentials"
	// DevicecontrolNewDeviceRequests — GET POST
	DevicecontrolNewDeviceRequests = "/devicecontrol/newDeviceRequests"
	// DevicecontrolNewDeviceRequestsRequestID — GET PUT DELETE
	DevicecontrolNewDeviceRequestsRequestID = "/devicecontrol/newDeviceRequests/{requestId}"
	// DevicecontrolOperations — GET POST DELETE
	DevicecontrolOperations = "/devicecontrol/operations"
	// DevicecontrolOperationsID — GET PUT
	DevicecontrolOperationsID = "/devicecontrol/operations/{id}"
	// Event — GET
	Event = "/event"
	// EventEvents — GET POST DELETE
	EventEvents = "/event/events"
	// EventEventsID — GET PUT DELETE
	EventEventsID = "/event/events/{id}"
	// EventEventsIDBinaries — GET PUT POST DELETE
	EventEventsIDBinaries = "/event/events/{id}/binaries"
	// Features — GET
	Features = "/features"
	// FeaturesFeatureKey — GET
	FeaturesFeatureKey = "/features/{featureKey}"
	// FeaturesFeatureKeyByTenant — GET PUT DELETE
	FeaturesFeatureKeyByTenant = "/features/{featureKey}/by-tenant"
	// FeaturesFeatureKeyByTenantTenantID — PUT DELETE
	FeaturesFeatureKeyByTenantTenantID = "/features/{featureKey}/by-tenant/{tenantId}"
	// Identity — GET
	Identity = "/identity"
	// IdentityExternalIdsTypeExternalID — GET DELETE
	IdentityExternalIdsTypeExternalID = "/identity/externalIds/{type}/{externalId}"
	// IdentityGlobalIdsIDExternalIds — GET POST
	IdentityGlobalIdsIDExternalIds = "/identity/globalIds/{id}/externalIds"
	// IdentitySearch — POST
	IdentitySearch = "/identity/search"
	// Inventory — GET
	Inventory = "/inventory"
	// InventoryBinaries — GET POST
	InventoryBinaries = "/inventory/binaries"
	// InventoryBinariesID — GET PUT DELETE
	InventoryBinariesID = "/inventory/binaries/{id}"
	// InventoryManagedObjects — GET PUT POST
	InventoryManagedObjects = "/inventory/managedObjects"
	// InventoryManagedObjectsID — GET PUT DELETE
	InventoryManagedObjectsID = "/inventory/managedObjects/{id}"
	// InventoryManagedObjectsIDAvailability — GET
	InventoryManagedObjectsIDAvailability = "/inventory/managedObjects/{id}/availability"
	// InventoryManagedObjectsIDChildAdditions — GET POST DELETE
	InventoryManagedObjectsIDChildAdditions = "/inventory/managedObjects/{id}/childAdditions"
	// InventoryManagedObjectsIDChildAdditionsChildID — GET DELETE
	InventoryManagedObjectsIDChildAdditionsChildID = "/inventory/managedObjects/{id}/childAdditions/{childId}"
	// InventoryManagedObjectsIDChildAssets — GET POST DELETE
	InventoryManagedObjectsIDChildAssets = "/inventory/managedObjects/{id}/childAssets"
	// InventoryManagedObjectsIDChildAssetsChildID — GET DELETE
	InventoryManagedObjectsIDChildAssetsChildID = "/inventory/managedObjects/{id}/childAssets/{childId}"
	// InventoryManagedObjectsIDChildDevices — GET POST DELETE
	InventoryManagedObjectsIDChildDevices = "/inventory/managedObjects/{id}/childDevices"
	// InventoryManagedObjectsIDChildDevicesChildID — GET DELETE
	InventoryManagedObjectsIDChildDevicesChildID = "/inventory/managedObjects/{id}/childDevices/{childId}"
	// InventoryManagedObjectsIDSupportedMeasurements — GET
	InventoryManagedObjectsIDSupportedMeasurements = "/inventory/managedObjects/{id}/supportedMeasurements"
	// InventoryManagedObjectsIDSupportedSeries — GET
	InventoryManagedObjectsIDSupportedSeries = "/inventory/managedObjects/{id}/supportedSeries"
	// InventoryManagedObjectsIDUser — GET PUT
	InventoryManagedObjectsIDUser = "/inventory/managedObjects/{id}/user"
	// Measurement — GET
	Measurement = "/measurement"
	// MeasurementMeasurements — GET POST DELETE
	MeasurementMeasurements = "/measurement/measurements"
	// MeasurementMeasurementsSeries — GET
	MeasurementMeasurementsSeries = "/measurement/measurements/series"
	// MeasurementMeasurementsID — GET DELETE
	MeasurementMeasurementsID = "/measurement/measurements/{id}"
	// NotificationRealtime — POST
	NotificationRealtime = "/notification/realtime"
	// Notification2 — GET
	Notification2 = "/notification2"
	// Notification2Subscriptions — GET POST DELETE
	Notification2Subscriptions = "/notification2/subscriptions"
	// Notification2SubscriptionsID — GET DELETE
	Notification2SubscriptionsID = "/notification2/subscriptions/{id}"
	// Notification2Token — POST
	Notification2Token = "/notification2/token"
	// Notification2Unsubscribe — POST
	Notification2Unsubscribe = "/notification2/unsubscribe"
	// Platform — GET
	Platform = "/platform"
	// RetentionRetentions — GET POST
	RetentionRetentions = "/retention/retentions"
	// RetentionRetentionsID — GET PUT DELETE
	RetentionRetentionsID = "/retention/retentions/{id}"
	// Tenant — GET
	Tenant = "/tenant"
	// TenantCurrentTenant — GET
	TenantCurrentTenant = "/tenant/currentTenant"
	// TenantLoginOptions — GET POST
	TenantLoginOptions = "/tenant/loginOptions"
	// TenantLoginOptionsTypeOrID — GET PUT DELETE
	TenantLoginOptionsTypeOrID = "/tenant/loginOptions/{typeOrId}"
	// TenantLoginOptionsTypeOrIDAccessMappings — GET POST
	TenantLoginOptionsTypeOrIDAccessMappings = "/tenant/loginOptions/{typeOrId}/accessMappings"
	// TenantLoginOptionsTypeOrIDAccessMappingsID — GET PUT DELETE
	TenantLoginOptionsTypeOrIDAccessMappingsID = "/tenant/loginOptions/{typeOrId}/accessMappings/{id}"
	// TenantLoginOptionsTypeOrIDInventoryAccessMappings — GET POST
	TenantLoginOptionsTypeOrIDInventoryAccessMappings = "/tenant/loginOptions/{typeOrId}/inventoryAccessMappings"
	// TenantLoginOptionsTypeOrIDInventoryAccessMappingsID — GET PUT DELETE
	TenantLoginOptionsTypeOrIDInventoryAccessMappingsID = "/tenant/loginOptions/{typeOrId}/inventoryAccessMappings/{id}"
	// TenantLoginOptionsTypeOrIDRestrict — PUT
	TenantLoginOptionsTypeOrIDRestrict = "/tenant/loginOptions/{typeOrId}/restrict"
	// TenantOAuth — POST
	TenantOAuth = "/tenant/oauth"
	// TenantOAuthToken — POST
	TenantOAuthToken = "/tenant/oauth/token"
	// TenantOptions — GET POST
	TenantOptions = "/tenant/options"
	// TenantOptionsCategory — GET PUT
	TenantOptionsCategory = "/tenant/options/{category}"
	// TenantOptionsCategoryKey — GET PUT DELETE
	TenantOptionsCategoryKey = "/tenant/options/{category}/{key}"
	// TenantOptionsCategoryKeyEditable — PUT
	TenantOptionsCategoryKeyEditable = "/tenant/options/{category}/{key}/editable"
	// TenantStatistics — GET
	TenantStatistics = "/tenant/statistics"
	// TenantStatisticsAllTenantsSummary — GET
	TenantStatisticsAllTenantsSummary = "/tenant/statistics/allTenantsSummary"
	// TenantStatisticsDeviceTenantIDDailyDate — GET
	TenantStatisticsDeviceTenantIDDailyDate = "/tenant/statistics/device/{tenantId}/daily/{date}"
	// TenantStatisticsDeviceTenantIDMonthlyDate — GET
	TenantStatisticsDeviceTenantIDMonthlyDate = "/tenant/statistics/device/{tenantId}/monthly/{date}"
	// TenantStatisticsFiles — GET POST
	TenantStatisticsFiles = "/tenant/statistics/files"
	// TenantStatisticsFilesLatestMonth — GET
	TenantStatisticsFilesLatestMonth = "/tenant/statistics/files/latest/{month}"
	// TenantStatisticsFilesID — GET
	TenantStatisticsFilesID = "/tenant/statistics/files/{id}"
	// TenantStatisticsSummary — GET
	TenantStatisticsSummary = "/tenant/statistics/summary"
	// TenantSystemOptions — GET
	TenantSystemOptions = "/tenant/system/options"
	// TenantSystemOptionsCategoryKey — GET
	TenantSystemOptionsCategoryKey = "/tenant/system/options/{category}/{key}"
	// TenantTenants — GET POST
	TenantTenants = "/tenant/tenants"
	// TenantTenantsTenantID — GET PUT DELETE
	TenantTenantsTenantID = "/tenant/tenants/{tenantId}"
	// TenantTenantsTenantIDApplications — GET POST
	TenantTenantsTenantIDApplications = "/tenant/tenants/{tenantId}/applications"
	// TenantTenantsTenantIDApplicationsApplicationID — DELETE
	TenantTenantsTenantIDApplicationsApplicationID = "/tenant/tenants/{tenantId}/applications/{applicationId}"
	// TenantTenantsTenantIDTFA — GET PUT
	TenantTenantsTenantIDTFA = "/tenant/tenants/{tenantId}/tfa"
	// TenantTenantsTenantIDTrustedCertificates — GET POST
	TenantTenantsTenantIDTrustedCertificates = "/tenant/tenants/{tenantId}/trusted-certificates"
	// TenantTenantsTenantIDTrustedCertificatesPopFingerprintConfirmed — POST
	TenantTenantsTenantIDTrustedCertificatesPopFingerprintConfirmed = "/tenant/tenants/{tenantId}/trusted-certificates-pop/{fingerprint}/confirmed"
	// TenantTenantsTenantIDTrustedCertificatesPopFingerprintPop — POST
	TenantTenantsTenantIDTrustedCertificatesPopFingerprintPop = "/tenant/tenants/{tenantId}/trusted-certificates-pop/{fingerprint}/pop"
	// TenantTenantsTenantIDTrustedCertificatesPopFingerprintVerificationCode — POST
	TenantTenantsTenantIDTrustedCertificatesPopFingerprintVerificationCode = "/tenant/tenants/{tenantId}/trusted-certificates-pop/{fingerprint}/verification-code"
	// TenantTenantsTenantIDTrustedCertificatesBulk — POST
	TenantTenantsTenantIDTrustedCertificatesBulk = "/tenant/tenants/{tenantId}/trusted-certificates/bulk"
	// TenantTenantsTenantIDTrustedCertificatesFingerprint — GET PUT DELETE
	TenantTenantsTenantIDTrustedCertificatesFingerprint = "/tenant/tenants/{tenantId}/trusted-certificates/{fingerprint}"
	// TenantTrustedCertificatesSettingsCRL — GET PUT
	TenantTrustedCertificatesSettingsCRL = "/tenant/trusted-certificates/settings/crl"
	// TenantTrustedCertificatesVerifyCertChain — POST
	TenantTrustedCertificatesVerifyCertChain = "/tenant/trusted-certificates/verify-cert-chain"
	// User — GET
	User = "/user"
	// UserCurrentUser — GET PUT
	UserCurrentUser = "/user/currentUser"
	// UserCurrentUserPassword — PUT
	UserCurrentUserPassword = "/user/currentUser/password"
	// UserCurrentUserTOTPSecret — POST
	UserCurrentUserTOTPSecret = "/user/currentUser/totpSecret"
	// UserCurrentUserTOTPSecretActivity — GET POST
	UserCurrentUserTOTPSecretActivity = "/user/currentUser/totpSecret/activity"
	// UserCurrentUserTOTPSecretVerify — POST
	UserCurrentUserTOTPSecretVerify = "/user/currentUser/totpSecret/verify"
	// UserDevicePermissionsID — GET PUT
	UserDevicePermissionsID = "/user/devicePermissions/{id}"
	// UserInventoryroles — GET POST
	UserInventoryroles = "/user/inventoryroles"
	// UserInventoryrolesID — GET PUT DELETE
	UserInventoryrolesID = "/user/inventoryroles/{id}"
	// UserLogout — POST
	UserLogout = "/user/logout"
	// UserLogoutTenantIDAllUsers — POST
	UserLogoutTenantIDAllUsers = "/user/logout/{tenantId}/allUsers"
	// UserRoles — GET
	UserRoles = "/user/roles"
	// UserRolesName — GET
	UserRolesName = "/user/roles/{name}"
	// UserTenantIDGroupByNameGroupName — GET
	UserTenantIDGroupByNameGroupName = "/user/{tenantId}/groupByName/{groupName}"
	// UserTenantIDGroups — GET POST
	UserTenantIDGroups = "/user/{tenantId}/groups"
	// UserTenantIDGroupsGroupID — GET PUT DELETE
	UserTenantIDGroupsGroupID = "/user/{tenantId}/groups/{groupId}"
	// UserTenantIDGroupsGroupIDRoles — GET POST
	UserTenantIDGroupsGroupIDRoles = "/user/{tenantId}/groups/{groupId}/roles"
	// UserTenantIDGroupsGroupIDRolesRoleID — DELETE
	UserTenantIDGroupsGroupIDRolesRoleID = "/user/{tenantId}/groups/{groupId}/roles/{roleId}"
	// UserTenantIDGroupsGroupIDUsers — GET POST
	UserTenantIDGroupsGroupIDUsers = "/user/{tenantId}/groups/{groupId}/users"
	// UserTenantIDGroupsGroupIDUsersUserID — DELETE
	UserTenantIDGroupsGroupIDUsersUserID = "/user/{tenantId}/groups/{groupId}/users/{userId}"
	// UserTenantIDUserByNameUsername — GET
	UserTenantIDUserByNameUsername = "/user/{tenantId}/userByName/{username}"
	// UserTenantIDUsers — GET POST
	UserTenantIDUsers = "/user/{tenantId}/users"
	// UserTenantIDUsersUserID — GET PUT DELETE
	UserTenantIDUsersUserID = "/user/{tenantId}/users/{userId}"
	// UserTenantIDUsersUserIDGroups — GET
	UserTenantIDUsersUserIDGroups = "/user/{tenantId}/users/{userId}/groups"
	// UserTenantIDUsersUserIDRoles — POST
	UserTenantIDUsersUserIDRoles = "/user/{tenantId}/users/{userId}/roles"
	// UserTenantIDUsersUserIDRolesInventory — GET POST
	UserTenantIDUsersUserIDRolesInventory = "/user/{tenantId}/users/{userId}/roles/inventory"
	// UserTenantIDUsersUserIDRolesInventoryID — GET PUT DELETE
	UserTenantIDUsersUserIDRolesInventoryID = "/user/{tenantId}/users/{userId}/roles/inventory/{id}"
	// UserTenantIDUsersUserIDRolesRoleID — DELETE
	UserTenantIDUsersUserIDRolesRoleID = "/user/{tenantId}/users/{userId}/roles/{roleId}"
	// UserTenantIDUsersUserIDTFA — GET
	UserTenantIDUsersUserIDTFA = "/user/{tenantId}/users/{userId}/tfa"
)
