// Code generated by tools/c8ygen; DO NOT EDIT.
//
// Source: docs/c8y-oas.yml
// Regenerate with: task generate  (or: go generate ./...)
//
// This file is the mechanical, 1:1-with-OAS substrate (Layer 0). The ergonomic
// public API (resolvers, option structs, upsert, iterators) is hand-written and
// lives outside this package. See docs/API_GEN.md.

package measurements

import (
	"time"

	"github.com/reubenmiller/go-c8y/v2/pkg/c8y/api/inventory/managedobjects"
	"github.com/reubenmiller/go-c8y/v2/pkg/c8y/api/pagination"
)

// ListOptions to use when searching for measurements.
//
// The struct shape is generated from the OpenAPI spec; the Source resolver
// field is a deliberate divergence (it accepts "name:"/"ext:"/"query:"
// strings, resolved by the List method). See docs/API_GEN.md.
type ListOptions struct {
	// Start date or date and time of the measurement.
	DateFrom time.Time `url:"dateFrom,omitempty,omitzero"`

	// End date or date and time of the measurement.
	DateTo time.Time `url:"dateTo,omitempty,omitzero"`

	// If you are using a range query (that is, at least one of the `dateFrom` or `dateTo` parameters is included in the request), then setting `revert=false` will sort the
	Revert bool `url:"revert,omitempty"`

	// Source device to filter measurements by.
	// Use the typed helpers: managedobjects.ByName, ByExternalID, ByQuery, ByID,
	// or cast a string variable with managedobjects.DeviceRef(id).
	Source managedobjects.DeviceRef `url:"source,omitempty"`

	// The type of measurement to search for.
	Type string `url:"type,omitempty"`

	// The specific series to search for.
	ValueFragmentSeries string `url:"valueFragmentSeries,omitempty"`

	// A characteristic which identifies the measurement.
	ValueFragmentType string `url:"valueFragmentType,omitempty"`

	pagination.PaginationOptions
}
