// Code generated by tools/c8ygen; DO NOT EDIT.
//
// Source: docs/c8y-oas.yml
// Regenerate with: task generate  (or: go generate ./...)
//
// This file is the mechanical, 1:1-with-OAS substrate (Layer 0). The ergonomic
// public API (resolvers, option structs, upsert, iterators) is hand-written and
// lives outside this package. See docs/API_GEN.md.

package operations

import (
	"time"

	"github.com/reubenmiller/go-c8y/v2/pkg/c8y/api/inventory/managedobjects"
	"github.com/reubenmiller/go-c8y/v2/pkg/c8y/api/pagination"
	"github.com/reubenmiller/go-c8y/v2/pkg/c8y/api/types"
)

// ListOptions to use when searching for operations.
//
// The struct shape is generated from the OpenAPI spec; the AgentID/DeviceID
// resolver fields are a deliberate divergence (they accept
// "name:"/"ext:"/"query:" strings, resolved by the List method).
// See docs/API_GEN.md.
type ListOptions struct {
	// An agent ID that may be part of the operation.
	// Use the typed helpers: managedobjects.ByName, ByExternalID, ByQuery, ByID,
	// or cast a string variable with managedobjects.DeviceRef(id).
	AgentID managedobjects.DeviceRef `url:"agentId,omitempty"`

	// The bulk operation ID that this operation belongs to.
	BulkOperationID int `url:"bulkOperationId,omitempty"`

	// Start date or date and time of the operation.
	DateFrom time.Time `url:"dateFrom,omitempty,omitzero"`

	// End date or date and time of the operation.
	DateTo time.Time `url:"dateTo,omitempty,omitzero"`

	// The ID of the device the operation is performed for.
	// Use the typed helpers: managedobjects.ByName, ByExternalID, ByQuery, ByID,
	// or cast a string variable with managedobjects.DeviceRef(id).
	DeviceID managedobjects.DeviceRef `url:"deviceId,omitempty"`

	// The type of fragment that must be part of the operation.
	FragmentType string `url:"fragmentType,omitempty"`

	// If you are using a range query (that is, at least one of the `dateFrom` or `dateTo` parameters is included in the request), then setting `revert=true` will sort the results by the newest operations first.
	Revert bool `url:"revert,omitempty"`

	// Status of the operation.
	Status types.OperationStatus `url:"status,omitempty"`

	pagination.PaginationOptions
}
