// Code generated by tools/c8ygen; DO NOT EDIT.
//
// Source: docs/c8y-oas.yml
// Regenerate with: task generate  (or: go generate ./...)
//
// This file is the mechanical, 1:1-with-OAS substrate (Layer 0). The ergonomic
// public API (resolvers, option structs, upsert, iterators) is hand-written and
// lives outside this package. See docs/API_GEN.md.

package alarms

import (
	"time"

	"github.com/reubenmiller/go-c8y/v2/pkg/c8y/api/inventory/managedobjects"
	"github.com/reubenmiller/go-c8y/v2/pkg/c8y/api/model"
	"github.com/reubenmiller/go-c8y/v2/pkg/c8y/api/pagination"
)

// ListOptions to use when searching for alarms.
//
// The struct shape is generated from the OpenAPI spec; the Source resolver
// field is a deliberate divergence (it accepts "name:"/"ext:"/"query:"
// strings, resolved by the List method). See docs/API_GEN.md.
type ListOptions struct {
	// Start date or date and time of the alarm creation.
	CreatedFrom time.Time `url:"createdFrom,omitempty,omitzero"`

	// End date or date and time of the alarm creation.
	CreatedTo time.Time `url:"createdTo,omitempty,omitzero"`

	// Start date or date and time of the alarm occurrence.
	DateFrom time.Time `url:"dateFrom,omitempty,omitzero" layout:"2006-01-02T15:04:05.000Z07:00"`

	// End date or date and time of the alarm occurrence.
	DateTo time.Time `url:"dateTo,omitempty,omitzero" layout:"2006-01-02T15:04:05.000Z07:00"`

	// Start date or date and time of the last update made.
	LastUpdatedFrom time.Time `url:"lastUpdatedFrom,omitempty,omitzero"`

	// End date or date and time of the last update made.
	LastUpdatedTo time.Time `url:"lastUpdatedTo,omitempty,omitzero"`

	// When set to `true` only alarms with status CLEARED will be fetched, whereas `false` will fetch all alarms with status ACTIVE or ACKNOWLEDGED. Takes precedence over the `status` parameter.
	Resolved bool `url:"resolved,omitempty"`

	// The severity of the alarm to search for.
	Severity []model.AlarmSeverity `url:"severity,omitempty"`

	// Source device to filter alarms by.
	// Use the typed helpers: managedobjects.ByName, ByExternalID, ByQuery, ByID,
	// or cast a string variable with managedobjects.DeviceRef(id).
	Source managedobjects.DeviceRef `url:"source,omitempty"`

	// The status of the alarm to search for. Should not be used when `resolved` parameter is provided.
	Status []model.AlarmStatus `url:"status,omitempty"`

	// The types of alarm to search for.
	Type []string `url:"type,omitempty"`

	// When set to `true`, alarms for related source assets, devices and additions will also be included in the response. When this parameter is provided a `source` must be specified.
	WithSourceChildren bool `url:"withSourceChildren,omitempty"`

	// When set to `true`, alarms for related source assets will also be included in the response. When this parameter is provided a `source` must be specified.
	WithSourceAssets bool `url:"withSourceAssets,omitempty"`

	// When set to `true`, alarms for related source devices will also be included in the response. When this parameter is provided a `source` must be specified.
	WithSourceDevices bool `url:"withSourceDevices,omitempty"`

	// When set to `true`, alarms for related source additions will also be included in the response. When this parameter is provided a `source` must be specified.
	WithSourceAdditions bool `url:"withSourceAdditions,omitempty"`

	pagination.PaginationOptions
}
