package main

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// generatedHeader is prepended to every emitted file.
func generatedHeader(pkg, source string) string {
	return fmt.Sprintf(`// Code generated by tools/c8ygen; DO NOT EDIT.
//
// Source: %s
// Regenerate with: task generate  (or: go generate ./...)
//
// This file is the mechanical, 1:1-with-OAS substrate (Layer 0). The ergonomic
// public API (resolvers, option structs, upsert, iterators) is hand-written and
// lives outside this package. See docs/API_GEN.md.

package %s
`, source, pkg)
}

// pathEntry is one generated path constant.
type pathEntry struct {
	Ident   string
	Path    string
	Comment string
}

// collectPaths builds the sorted, de-duplicated set of path constants.
func collectPaths(doc *OAS) []pathEntry {
	seen := map[string]bool{}
	entries := []pathEntry{}
	for _, path := range sortedKeys(doc.Paths) {
		ident := pathIdent(path)
		// Guard against the (rare) ident collision by suffixing.
		base := ident
		for i := 2; seen[ident]; i++ {
			ident = fmt.Sprintf("%s%d", base, i)
		}
		seen[ident] = true

		comment := summarize(doc.Paths[path])
		entries = append(entries, pathEntry{Ident: ident, Path: path, Comment: comment})
	}
	return entries
}

// summarize produces a short comment for a path from its operations' methods.
func summarize(item PathItem) string {
	methods := []string{}
	for _, mo := range item.Operations() {
		methods = append(methods, mo.Method)
	}
	if len(methods) == 0 {
		return ""
	}
	return strings.Join(methods, " ")
}

// enumGroup is one generated enum type with its string values.
type enumGroup struct {
	Name   string
	Values []enumValue
}

type enumValue struct {
	Ident string
	Value string
}

// collectEnums walks the component schemas and emits a typed string enum for every
// property (or top-level schema) that declares a string enum.
func collectEnums(doc *OAS) []enumGroup {
	groups := map[string]enumGroup{}

	for _, name := range sortedKeys(doc.Components.Schemas) {
		schema := doc.Components.Schemas[name]
		walkEnums(pascalAll(name), schema, groups, 0)
	}

	out := make([]enumGroup, 0, len(groups))
	for _, k := range sortedKeys(groups) {
		out = append(out, groups[k])
	}
	return out
}

// walkEnums recursively descends a schema collecting string enums. $ref nodes are not
// followed (enums in this spec are declared inline). Recursion is depth-bounded.
func walkEnums(prefix string, s Schema, groups map[string]enumGroup, depth int) {
	if depth > 4 {
		return
	}
	if strs, ok := stringEnum(s); ok {
		addEnumGroup(prefix, strs, groups)
	}
	for _, propName := range sortedKeys(s.Properties) {
		walkEnums(prefix+pascalAll(propName), s.Properties[propName], groups, depth+1)
	}
	if s.Items != nil {
		walkEnums(prefix+"Item", *s.Items, groups, depth+1)
	}
}

// stringEnum returns the enum values if the schema declares an all-string enum.
func stringEnum(s Schema) ([]string, bool) {
	if len(s.Enum) == 0 {
		return nil, false
	}
	out := make([]string, 0, len(s.Enum))
	for _, v := range s.Enum {
		str, ok := v.(string)
		if !ok {
			return nil, false // mixed/non-string enum: skip
		}
		out = append(out, str)
	}
	return out, len(out) > 0
}

// addEnumGroup registers an enum group, de-duplicating by name. A name collision with a
// different value-set is disambiguated with a numeric suffix.
func addEnumGroup(name string, values []string, groups map[string]enumGroup) {
	g := enumGroup{Name: name}
	for _, v := range values {
		g.Values = append(g.Values, enumValue{Ident: name + enumValueIdent(v), Value: v})
	}
	final := name
	for i := 2; ; i++ {
		existing, ok := groups[final]
		if !ok {
			break
		}
		if sameValues(existing, g) {
			return // identical enum already registered
		}
		final = fmt.Sprintf("%s%d", name, i)
		g.Name = final
		for j, v := range values {
			g.Values[j].Ident = final + enumValueIdent(v)
		}
	}
	groups[final] = g
}

func sameValues(a, b enumGroup) bool {
	if len(a.Values) != len(b.Values) {
		return false
	}
	av := make([]string, len(a.Values))
	bv := make([]string, len(b.Values))
	for i := range a.Values {
		av[i] = a.Values[i].Value
		bv[i] = b.Values[i].Value
	}
	sort.Strings(av)
	sort.Strings(bv)
	for i := range av {
		if av[i] != bv[i] {
			return false
		}
	}
	return true
}

// enumValueIdent turns an enum value into an identifier fragment, e.g. "CLEARED" ->
// "Cleared", "application/json" -> "ApplicationJSON".
func enumValueIdent(v string) string {
	var b strings.Builder
	for _, tok := range splitToken(v) {
		b.WriteString(pascal(strings.ToLower(tok)))
	}
	id := b.String()
	if id == "" {
		return "Empty"
	}
	return id
}

// GenerateResult reports what was written.
type GenerateResult struct {
	Files []string
	Paths int
	Enums int
}

// Generate emits the Layer-0 files into outDir.
func Generate(doc *OAS, source, outDir string) (GenerateResult, error) {
	res := GenerateResult{}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return res, err
	}

	paths := collectPaths(doc)
	enums := collectEnums(doc)
	res.Paths = len(paths)
	res.Enums = len(enums)

	pathsFile := filepath.Join(outDir, "zz_generated_paths.go")
	if err := writeFormatted(pathsFile, renderPaths(source, paths)); err != nil {
		return res, err
	}
	res.Files = append(res.Files, pathsFile)

	enumsFile := filepath.Join(outDir, "zz_generated_enums.go")
	if err := writeFormatted(enumsFile, renderEnums(source, enums)); err != nil {
		return res, err
	}
	res.Files = append(res.Files, enumsFile)

	return res, nil
}

func renderPaths(source string, entries []pathEntry) string {
	var b strings.Builder
	b.WriteString(generatedHeader("spec", source))
	b.WriteString("\n// Path constants for Cumulocity REST API endpoints.\n")
	b.WriteString("// Placeholders ({id}, {childId}, ...) are filled at request time via SetPathParam.\n")
	b.WriteString("const (\n")
	for _, e := range entries {
		if e.Comment != "" {
			fmt.Fprintf(&b, "\t// %s — %s\n", e.Ident, e.Comment)
		}
		fmt.Fprintf(&b, "\t%s = %q\n", e.Ident, e.Path)
	}
	b.WriteString(")\n")
	return b.String()
}

func renderEnums(source string, groups []enumGroup) string {
	var b strings.Builder
	b.WriteString(generatedHeader("spec", source))
	b.WriteString("\n// Enum value constants derived from the OpenAPI schema definitions.\n")
	for _, g := range groups {
		fmt.Fprintf(&b, "\n// %s enumerates the values for the %s field.\n", g.Name, g.Name)
		fmt.Fprintf(&b, "type %s = string\n\n", g.Name)
		b.WriteString("const (\n")
		for _, v := range g.Values {
			fmt.Fprintf(&b, "\t%s %s = %q\n", v.Ident, g.Name, v.Value)
		}
		b.WriteString(")\n")
	}
	return b.String()
}

// writeFormatted gofmt's the source then writes it. On a format error the raw source is
// written so the failure is debuggable.
func writeFormatted(path, src string) error {
	formatted, err := format.Source([]byte(src))
	if err != nil {
		_ = os.WriteFile(path, []byte(src), 0o644)
		return fmt.Errorf("gofmt %s: %w", path, err)
	}
	return os.WriteFile(path, formatted, 0o644)
}
