// Code generated by tools/c8ygen; DO NOT EDIT.
//
// Source: docs/c8y-oas.yml
// Regenerate with: task generate  (or: go generate ./...)
//
// This file is the mechanical, 1:1-with-OAS substrate (Layer 0). The ergonomic
// public API (resolvers, option structs, upsert, iterators) is hand-written and
// lives outside this package. See docs/API_GEN.md.

package events

import (
	"time"

	"github.com/reubenmiller/go-c8y/v2/pkg/c8y/api/inventory/managedobjects"
	"github.com/reubenmiller/go-c8y/v2/pkg/c8y/api/pagination"
)

// ListOptions to use when searching for events.
//
// The struct shape is generated from the OpenAPI spec; the Source resolver
// field is a deliberate divergence (it accepts "name:"/"ext:"/"query:"
// strings, resolved by the List method). See docs/API_GEN.md.
type ListOptions struct {
	// Start date or date and time of the event's creation (set by the platform during creation).
	CreatedFrom time.Time `url:"createdFrom,omitempty,omitzero"`

	// End date or date and time of the event's creation (set by the platform during creation).
	CreatedTo time.Time `url:"createdTo,omitempty,omitzero"`

	// Start date or date and time of the event occurrence (provided by the device).
	DateFrom time.Time `url:"dateFrom,omitempty,omitzero" layout:"2006-01-02T15:04:05.000Z07:00"`

	// End date or date and time of the event occurrence (provided by the device).
	DateTo time.Time `url:"dateTo,omitempty,omitzero" layout:"2006-01-02T15:04:05.000Z07:00"`

	// A characteristic which identifies a managed object or event, for example, geolocation, electricity sensor, relay state.
	FragmentType string `url:"fragmentType,omitempty"`

	// Allows filtering events by the fragment's value, but only when provided together with `fragmentType`.
	FragmentValue string `url:"fragmentValue,omitempty"`

	// Start date or date and time of the last update made.
	LastUpdatedFrom time.Time `url:"lastUpdatedFrom,omitempty,omitzero"`

	// End date or date and time of the last update made.
	LastUpdatedTo time.Time `url:"lastUpdatedTo,omitempty,omitzero"`

	// If you are using a range query (that is, at least one of the `dateFrom` or `dateTo` parameters is included in the request), then setting `revert=true` will sort the results by the oldest events first.
	Revert bool `url:"revert,omitempty"`

	// Source device to filter events by.
	// Use the typed helpers: managedobjects.ByName, ByExternalID, ByQuery, ByID,
	// or cast a string variable with managedobjects.DeviceRef(id).
	Source managedobjects.DeviceRef `url:"source,omitempty"`

	// The type of event to search for.
	Type string `url:"type,omitempty"`

	// When set to `true`, events for related source assets, devices and additions will also be included in the response. When this parameter is provided a `source` must be specified.
	WithSourceChildren bool `url:"withSourceChildren,omitempty"`

	// When set to `true`, events for related source assets will also be included in the response. When this parameter is provided a `source` must be specified.
	WithSourceAssets bool `url:"withSourceAssets,omitempty"`

	// When set to `true`, events for related source devices will also be included in the response. When this parameter is provided a `source` must be specified.
	WithSourceDevices bool `url:"withSourceDevices,omitempty"`

	// When set to `true`, events for related source additions will also be included in the response. When this parameter is provided a `source` must be specified.
	WithSourceAdditions bool `url:"withSourceAdditions,omitempty"`

	pagination.PaginationOptions
}
