// Code generated by tools/c8ygen; DO NOT EDIT.
//
// Source: docs/c8y-oas.yml
// Regenerate with: task generate  (or: go generate ./...)
//
// This file is the mechanical, 1:1-with-OAS substrate (Layer 0). The ergonomic
// public API (resolvers, option structs, upsert, iterators) is hand-written and
// lives outside this package. See docs/API_GEN.md.

package jsonmodels

import "time"

// Generated façade accessors for the "measurement" schema. Nested-object and non-derivable
// accessors (e.g. SourceID) and constructors are hand-written in measurement.go.

// ID Unique identifier of the measurement.
func (m Measurement) ID() string { return m.Get("id").String() }

func (m Measurement) Self() string { return m.Get("self").String() }

// Time The date and time when the measurement is created.
func (m Measurement) Time() time.Time { return m.Get("time").Time() }

// Type Identifies the type of this measurement.
func (m Measurement) Type() string { return m.Get("type").String() }
