// Code generated by tools/c8ygen; DO NOT EDIT.
//
// Source: docs/c8y-oas.yml
// Regenerate with: task generate  (or: go generate ./...)
//
// This file is the mechanical, 1:1-with-OAS substrate (Layer 0). The ergonomic
// public API (resolvers, option structs, upsert, iterators) is hand-written and
// lives outside this package. See docs/API_GEN.md.

package jsonmodels

import "time"

// Generated façade accessors for the "operation" schema. Nested-object and non-derivable
// accessors (e.g. SourceID) and constructors are hand-written in operation.go.

// BulkOperationID Reference to a bulk operation ID if this operation was scheduled from a bulk operation.
func (m Operation) BulkOperationID() int64 { return m.Get("bulkOperationId").Int() }

// CreationTime Date and time when the operation was created in the database.
func (m Operation) CreationTime() time.Time { return m.Get("creationTime").Time() }

// DeviceID Identifier of the target device where the operation should be performed.
func (m Operation) DeviceID() string { return m.Get("deviceId").String() }

// FailureReason Reason for the failure.
func (m Operation) FailureReason() string { return m.Get("failureReason").String() }

// ID Unique identifier of this operation.
func (m Operation) ID() string { return m.Get("id").String() }

func (m Operation) Self() string { return m.Get("self").String() }

// Status The status of the operation.
func (m Operation) Status() string { return m.Get("status").String() }
