// Code generated by tools/c8ygen; DO NOT EDIT.
//
// Source: docs/c8y-oas.yml
// Regenerate with: task generate  (or: go generate ./...)
//
// This file is the mechanical, 1:1-with-OAS substrate (Layer 0). The ergonomic
// public API (resolvers, option structs, upsert, iterators) is hand-written and
// lives outside this package. See docs/API_GEN.md.

package jsonmodels

import "time"

// Generated façade accessors for the "alarm" schema. Nested-object and non-derivable
// accessors (e.g. SourceID) and constructors are hand-written in alarm.go.

// Count Number of times that this alarm has been triggered.
func (m Alarm) Count() int64 { return m.Get("count").Int() }

// CreationTime The date and time when the alarm was created.
func (m Alarm) CreationTime() time.Time { return m.Get("creationTime").Time() }

// FirstOccurrenceTime The time at which the alarm occurred for the first time. Only present when `count` is greater than 1.
func (m Alarm) FirstOccurrenceTime() time.Time { return m.Get("firstOccurrenceTime").Time() }

// ID Unique identifier of the alarm.
func (m Alarm) ID() string { return m.Get("id").String() }

// LastUpdated The date and time when the alarm was last updated.
func (m Alarm) LastUpdated() time.Time { return m.Get("lastUpdated").Time() }

func (m Alarm) Self() string { return m.Get("self").String() }

// Severity The severity of the alarm.
func (m Alarm) Severity() string { return m.Get("severity").String() }

// Status The status of the alarm. If not specified, a new alarm will be created as ACTIVE.
func (m Alarm) Status() string { return m.Get("status").String() }

// Text Description of the alarm.
func (m Alarm) Text() string { return m.Get("text").String() }

// Time The date and time when the alarm is triggered.
func (m Alarm) Time() time.Time { return m.Get("time").Time() }

// Type Identifies the type of this alarm.
func (m Alarm) Type() string { return m.Get("type").String() }
