// Code generated by tools/c8ygen; DO NOT EDIT.
//
// Source: docs/c8y-oas.yml
// Regenerate with: task generate  (or: go generate ./...)
//
// This file is the mechanical, 1:1-with-OAS substrate (Layer 0). The ergonomic
// public API (resolvers, option structs, upsert, iterators) is hand-written and
// lives outside this package. See docs/API_GEN.md.

package jsonmodels

import "time"

// Generated façade accessors for the "event" schema. Nested-object and non-derivable
// accessors (e.g. SourceID) and constructors are hand-written in event.go.

// CreationTime The date and time when the event was created.
func (m Event) CreationTime() time.Time { return m.Get("creationTime").Time() }

// ID Unique identifier of the event.
func (m Event) ID() string { return m.Get("id").String() }

// LastUpdated The date and time when the event was last updated.
func (m Event) LastUpdated() time.Time { return m.Get("lastUpdated").Time() }

func (m Event) Self() string { return m.Get("self").String() }

// Text Description of the event.
func (m Event) Text() string { return m.Get("text").String() }

// Time The date and time when the event is updated.
func (m Event) Time() time.Time { return m.Get("time").Time() }

// Type Identifies the type of this event.
func (m Event) Type() string { return m.Get("type").String() }
