name: pull-request-test

on:
  push:
    branches: [ master ]
    paths-ignore:
      - docs/*
      - '**/*.md'
      - test/*.go

  pull_request:
    branches: [ master ]

jobs:

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.29

          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          # args: --issues-exit-code=0

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true

  test:
    runs-on: ${{ matrix.os }}
    env:
      C8Y_HOST: ${{ secrets.C8Y_HOST }}
      C8Y_TENANT: ${{ secrets.C8Y_TENANT }}
      C8Y_USER: ${{ secrets.C8Y_USER }}
      C8Y_PASSWORD: ${{ secrets.C8Y_PASSWORD }}

      # Max timeout for each request (in milliseconds)
      C8Y_TIMEOUT: 30000

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-18.04]

    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14

    - uses: actions/checkout@v2

    - name: Run tests
      run: make test
